

 CREATE TABLE IF NOT EXISTS public.cards
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    card_number character varying(255) COLLATE pg_catalog."default",
    card_limit numeric(19,2),
    acount_id bigint,
    CONSTRAINT cards_pkey PRIMARY KEY (id),
    CONSTRAINT fkcspsk7wdiaxik5tekvfgjvgjq FOREIGN KEY (acount_id)
        REFERENCES public.accounts (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)}